# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-07-22 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_confirm_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='confirm_email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
