# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2019-07-21 04:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20190721_0610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to='media/images/'),
        ),
    ]
